### PR TITLE
Exponentiation in BigDouble

### PR DESCRIPTION
**Pull request by pgrela**

### CODE REVIEW

**Comment by mikera** [comment]
Hi @pregula, like the idea of adding a pow function!

However I'm a bit worried about losing precision by forcing the factor to be 1, 0 or -1. Did you see any reason why we can't just do something like `new BigDouble(factor, exponent * this.exponent)`?

Also I think it would be good to have a couple more test cases (for special cases like zero etc.). 

If you can do these then happy to merge!

**Comment by pgrela** [comment]
Hi,

if we don't normalise the factor, then exponentiation would have to be done like `new BigDouble(Math.pow(factor, exponent), exponent * this.exponent)` and I am working with really big exponents, so `Math.pow(factor, exponent)` can exceed Double.MAX_VALUE.
And writing some corner cases tests should be no problem.

Patryk

**Comment by mikera** [comment]
Ah OK - I am with you on the rationale.

Not quite sure of the best strategy.... perhaps some kind of range check to determine whether to normalise or not?

**Comment by mikera** [comment]
Thanks for the PR! Sorry didn't see this for quite some time....

**Pull request merged**
